/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ public enum a
/*     */ {
/* 592 */   a(new gc[] { gc.e, gc.f, gc.c, gc.d }, 0.5F, true, new eaz.e[] { eaz.e.k, eaz.e.d, eaz.e.k, eaz.e.j, eaz.e.e, eaz.e.j, eaz.e.e, eaz.e.d }, new eaz.e[] { eaz.e.k, eaz.e.c, eaz.e.k, eaz.e.i, eaz.e.e, eaz.e.i, eaz.e.e, eaz.e.c }, new eaz.e[] { eaz.e.l, eaz.e.c, eaz.e.l, eaz.e.i, eaz.e.f, eaz.e.i, eaz.e.f, eaz.e.c }, new eaz.e[] { eaz.e.l, eaz.e.d, eaz.e.l, eaz.e.j, eaz.e.f, eaz.e.j, eaz.e.f, eaz.e.d
/*     */ 
/*     */ 
/*     */ 
/*     */     
/*     */     }),
/* 598 */   b(new gc[] { gc.f, gc.e, gc.c, gc.d }, 1.0F, true, new eaz.e[] { eaz.e.f, eaz.e.d, eaz.e.f, eaz.e.j, eaz.e.l, eaz.e.j, eaz.e.l, eaz.e.d }, new eaz.e[] { eaz.e.f, eaz.e.c, eaz.e.f, eaz.e.i, eaz.e.l, eaz.e.i, eaz.e.l, eaz.e.c }, new eaz.e[] { eaz.e.e, eaz.e.c, eaz.e.e, eaz.e.i, eaz.e.k, eaz.e.i, eaz.e.k, eaz.e.c }, new eaz.e[] { eaz.e.e, eaz.e.d, eaz.e.e, eaz.e.j, eaz.e.k, eaz.e.j, eaz.e.k, eaz.e.d
/*     */ 
/*     */ 
/*     */ 
/*     */     
/*     */     }),
/* 604 */   c(new gc[] { gc.b, gc.a, gc.f, gc.e }, 0.8F, true, new eaz.e[] { eaz.e.b, eaz.e.k, eaz.e.b, eaz.e.e, eaz.e.h, eaz.e.e, eaz.e.h, eaz.e.k }, new eaz.e[] { eaz.e.b, eaz.e.l, eaz.e.b, eaz.e.f, eaz.e.h, eaz.e.f, eaz.e.h, eaz.e.l }, new eaz.e[] { eaz.e.a, eaz.e.l, eaz.e.a, eaz.e.f, eaz.e.g, eaz.e.f, eaz.e.g, eaz.e.l }, new eaz.e[] { eaz.e.a, eaz.e.k, eaz.e.a, eaz.e.e, eaz.e.g, eaz.e.e, eaz.e.g, eaz.e.k
/*     */ 
/*     */ 
/*     */ 
/*     */     
/*     */     }),
/* 610 */   d(new gc[] { gc.e, gc.f, gc.a, gc.b }, 0.8F, true, new eaz.e[] { eaz.e.b, eaz.e.k, eaz.e.h, eaz.e.k, eaz.e.h, eaz.e.e, eaz.e.b, eaz.e.e }, new eaz.e[] { eaz.e.a, eaz.e.k, eaz.e.g, eaz.e.k, eaz.e.g, eaz.e.e, eaz.e.a, eaz.e.e }, new eaz.e[] { eaz.e.a, eaz.e.l, eaz.e.g, eaz.e.l, eaz.e.g, eaz.e.f, eaz.e.a, eaz.e.f }, new eaz.e[] { eaz.e.b, eaz.e.l, eaz.e.h, eaz.e.l, eaz.e.h, eaz.e.f, eaz.e.b, eaz.e.f
/*     */ 
/*     */ 
/*     */ 
/*     */     
/*     */     }),
/* 616 */   e(new gc[] { gc.b, gc.a, gc.c, gc.d }, 0.6F, true, new eaz.e[] { eaz.e.b, eaz.e.d, eaz.e.b, eaz.e.j, eaz.e.h, eaz.e.j, eaz.e.h, eaz.e.d }, new eaz.e[] { eaz.e.b, eaz.e.c, eaz.e.b, eaz.e.i, eaz.e.h, eaz.e.i, eaz.e.h, eaz.e.c }, new eaz.e[] { eaz.e.a, eaz.e.c, eaz.e.a, eaz.e.i, eaz.e.g, eaz.e.i, eaz.e.g, eaz.e.c }, new eaz.e[] { eaz.e.a, eaz.e.d, eaz.e.a, eaz.e.j, eaz.e.g, eaz.e.j, eaz.e.g, eaz.e.d
/*     */ 
/*     */ 
/*     */ 
/*     */     
/*     */     }),
/* 622 */   f(new gc[] { gc.a, gc.b, gc.c, gc.d }, 0.6F, true, new eaz.e[] { eaz.e.g, eaz.e.d, eaz.e.g, eaz.e.j, eaz.e.a, eaz.e.j, eaz.e.a, eaz.e.d }, new eaz.e[] { eaz.e.g, eaz.e.c, eaz.e.g, eaz.e.i, eaz.e.a, eaz.e.i, eaz.e.a, eaz.e.c }, new eaz.e[] { eaz.e.h, eaz.e.c, eaz.e.h, eaz.e.i, eaz.e.b, eaz.e.i, eaz.e.b, eaz.e.c }, new eaz.e[] { eaz.e.h, eaz.e.d, eaz.e.h, eaz.e.j, eaz.e.b, eaz.e.j, eaz.e.b, eaz.e.d });
/*     */   
/*     */   private final gc[] g;
/*     */   
/*     */   private final boolean h;
/*     */   
/*     */   private final eaz.e[] i;
/*     */   
/*     */   private final eaz.e[] j;
/*     */   private final eaz.e[] k;
/*     */   private final eaz.e[] l;
/*     */   private static final a[] m;
/*     */   
/*     */   static {
/* 636 */     m = x.<a[]>a(new a[6], ☃ -> {
/*     */           ☃[gc.a.c()] = a;
/*     */           ☃[gc.b.c()] = b;
/*     */           ☃[gc.c.c()] = c;
/*     */           ☃[gc.d.c()] = d;
/*     */           ☃[gc.e.c()] = e;
/*     */           ☃[gc.f.c()] = f;
/*     */         });
/*     */   }
/*     */   a(gc[] ☃, float f, boolean bool, eaz.e[] arrayOfE1, eaz.e[] arrayOfE2, eaz.e[] arrayOfE3, eaz.e[] arrayOfE4) {
/* 646 */     this.g = ☃;
/* 647 */     this.h = bool;
/* 648 */     this.i = arrayOfE1;
/* 649 */     this.j = arrayOfE2;
/* 650 */     this.k = arrayOfE3;
/* 651 */     this.l = arrayOfE4;
/*     */   }
/*     */   
/*     */   public static a a(gc ☃) {
/* 655 */     return m[☃.c()];
/*     */   }
/*     */ }


/* Location:              C:\Users\Georg\OneDrive\Minecraft\Desktop\Minecraft\1.16.4.zip!\eaz$a.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */